[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Freightol"
authors = [{name = "Graziella", email = "it@freightol.com"}]
dynamic = ["version", "description"]
